#!/usr/bin/env bash
# use -c and a number to make the ping command stop automatically after 
# sending a certain number of packets.
if [ "$1" ]; then
    ping -c 5 "$1"
else
# $1 is the first argument
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
