#!/usr/bin/env bash
# display Holberton School, but for the 4th iteration print "bad luck" and the 8th "good luck"

COUNT=0
while [ $COUNT -lt 10 ]; do
    ((COUNT++))
    if [ "$COUNT" == 4 ]
    then
        echo "bad luck"
    elif [ "$COUNT" == 8 ]
    then
        echo "good luck"
    else
        echo "Holberton School"
    fi
done
