#!/usr/bin/env bash
# SED command:Can do insertion, deletion, search 
# and replace(substitution)

cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/" ~/hosts.new
echo -e "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
