#!/usr/bin/env bash
# Nginx is running as the nginx user.

# create a new user without sudo privileges, This is done via the user directive.
sudo sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf

# Listen port 8080
sudo sed -i 's/80/8080/g' /etc/nginx/sites-available/default

sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill -f apache2

# run whit user nginx
sudo -u nginx service nginx restart
